config/routes.rb
Rails.application.routes.draw do

  concern :get_modal do
    get 'modal/:id/:button/:form', action: 'modal', as: 'modal', on: :collection
  end
  
  resources :payment_methods
  resources :accounts
  resources :cierres
  resources :auth_groups
  resources :employees, concerns: :get_modal
  resources :retenciones
  resources :inversions, concerns: :get_modal
  resources :ggs, concerns: :get_modal
  resources :deducciones_odts
  resources :comision_odts
  resources :odts, concerns: :get_modal
  resources :razon_socials, concerns: :get_modal
  resources :pools, concerns: :get_modal do
    get 'account/:id', action: 'account_index', as: 'account', on: :collection
    get 'account/:id/days/:days', action: 'days_index', as: 'days_account', on: :collection
  end
  root "pools#days_index", :id => 1, :days => 0

  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/approve/:token', to: 'permission_request#approve'
  get '/deny/:token', to: 'permission_request#deny'
  get '/ask', to: 'permission_request#ask', as: :ask_permission
  post '/set_permission', to: 'permission_request#set_permission'

end

app/models/payment_method.rb
class PaymentMethod < ActiveRecord::Base
  belongs_to :account
  has_many :pools
  enum status: ["Inactiva","Activa"]

  def record_name_to_show
    return self.method
  end
  
  def table_name_to_show
    'Métodos de pago'
  end
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: [:show, :edit, :update, :destroy]

  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all
    @new_payment_method = PaymentMethod.new
    @new_payment_method.status="Activa"
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to payment_methods_url, success: 'El método de pago fue creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @payment_method }
      else
        format.html { render :new }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1
  # PATCH/PUT /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to payment_methods_url, success: 'El método de pago fue actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @payment_method }
      else
        format.html { render :edit }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url, success: 'El método de pago fue eliminado satisfactoriamente.' }
      format.json { head :no_content }
      format.js   { render 'layouts/destroy' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = PaymentMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_method_params
      params.require(:payment_method).permit(:account_id, :method, :status)
    end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/_form.html.erb
<%= form_for(@payment_method, namespace: namespace_id, :html=> {:id => namespace_id}) do |f| %>
  <% if @payment_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment_method.errors.count, "error") %> prohibited this payment_method from being saved:</h2>

      <ul>
      <% @payment_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :account_id, "Cuenta", class: "control-label" %><br>
    </div>
    <div class="col-sm-8">
      <%= f.collection_select( :account_id, Account.all, :id, :record_name_to_show, { prompt: '-Seleccionar-'}, { class: "form-control c-select chosen-select" }) %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :method, "Método", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :method, class: "form-control", :required => true %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :status, "Estado", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.collection_select( :status, PaymentMethod.statuses, :first, :first, { prompt: '-Seleccionar-'}, { class: "form-control c-select chosen-select" }) %>
    </div>
  </div>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editing Payment Method</h1>

<%= render 'form' %>

<%= link_to 'Show', @payment_method %> |
<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= PaymentMethod.new.table_name_to_show %></h1>
<p>
  <%= render "layouts/modal_button", :btn_name => 'Nuevo Registro', :namespace_id => 'new_payment_method' %>
  <%= render "layouts/modal", :@payment_method => @new_payment_method, :modal_title => 'Nuevo Registro', :namespace_id => 'new_payment_method' %>
</p>
<div class="table-responsive">
  <table class="table table-sm table-hover table-striped table-bordered">
    <thead>
      <tr>
        <th>Cuenta</th>
        <th>Método</th>
        <th>Estado</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @payment_methods.reverse.each do |payment_method| %>
        <tr>
          <td><%= payment_method.account.record_name_to_show %></td>
          <td><%= payment_method.method %></td>
          <td><%= payment_method.status %></td>
          <td>
            <%= render "layouts/modal_button", :btn_name => 'Editar', :namespace_id => "edit_payment_method_#{payment_method.id}" %>
            <%= render "layouts/modal", :@payment_method => payment_method, :modal_title => 'Editar', :namespace_id => "edit_payment_method_#{payment_method.id}" %>
          </td>
          <td><%= link_to '×', payment_method, method: :delete, data: { confirm: '¿Está seguro?' }, :remote => true, class: "close equis delete_row" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/payment_methods/new.html.erb
<h1>New Payment Method</h1>

<%= render 'form' %>

<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Account:</strong>
  <%= @payment_method.account %>
</p>

<p>
  <strong>Method:</strong>
  <%= @payment_method.method %>
</p>

<p>
  <strong>Status:</strong>
  <%= @payment_method.status %>
</p>

<%= link_to 'Edit', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Back', payment_methods_path %>