config/routes.rb
Rails.application.routes.draw do

  concern :get_modal do
    get 'modal/:id/:button/:form', action: 'modal', as: 'modal', on: :collection
  end
  
  resources :payment_methods
  resources :accounts
  resources :cierres
  resources :auth_groups
  resources :employees, concerns: :get_modal
  resources :retenciones
  resources :inversions, concerns: :get_modal
  resources :ggs, concerns: :get_modal
  resources :deducciones_odts
  resources :comision_odts
  resources :odts, concerns: :get_modal
  resources :razon_socials, concerns: :get_modal
  resources :pools, concerns: :get_modal do
    get 'account/:id', action: 'account_index', as: 'account', on: :collection
    get 'account/:id/days/:days', action: 'days_index', as: 'days_account', on: :collection
  end
  root "pools#days_index", :id => 1, :days => 0

  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/approve/:token', to: 'permission_request#approve'
  get '/deny/:token', to: 'permission_request#deny'
  get '/ask', to: 'permission_request#ask', as: :ask_permission
  post '/set_permission', to: 'permission_request#set_permission'

end

app/models/employee.rb
class Employee < ActiveRecord::Base 
	validates_presence_of :name, presence: true, :message => "no puede estar vacío"
	validates_presence_of :cedula, presence: true, :message => "no puede estar vacío"
	validates_presence_of  :last_name, presence: true, :message => "no puede estar vacío"
	validates_presence_of  :email, presence: true, :message => "no puede estar vacío"

	has_many :comision_odts
	has_many :odts, through: :comision_odts
	has_many :pools, as: :category
	has_one :user

	def has_auth_to(action)
		self.auth_groups.each do |group|
			case group[action]
			when true
				return true 
			when false
				return false
			when nil
				return 'Action "'+action.to_s+'" not found'
			else
				return 'Not boolean'
			end
		end
	end

  def get_loan_balance
    montos = self.pools.collect do |x|
      p x.monto
    end
    balance = montos.sum
    self.loan_balance = balance
  end

	def description
		return "Préstamo de #{self.record_name_to_show}"
	end
	def category_name_to_show
	'Préstamo'
	end
	def table_name_to_show
		'Empleado'
	end
	def record_name_to_show
		return self.name+' '+self.last_name
	end	
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :authenticate_user! #, except: [:index]
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    permission_denied and return  if current_user.cannot 'read_employee'
    @employees = Employee.all
    @new_employee = Employee.new
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    permission_denied and return  if current_user.cannot 'create_employee'
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_url, success: @employee.table_name_to_show.concat(' fue creado satisfactoriamente.') }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    permission_denied and return  if current_user.cannot 'update_employee'

    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to employees_url, success: @employee.table_name_to_show.concat(' fue actualizado satisfactoriamente.') }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    permission_denied and return  if current_user.cannot 'destroy_employee'
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, success: @employee.table_name_to_show.concat(' fue eliminado satisfactoriamente.') }
      format.json { head :no_content }
      format.js   { render 'layouts/destroy' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:cedula, :name, :last_name, :phone_number, :email, :address, :startdate, :note)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee, namespace: namespace_id, :html=> {:id => namespace_id}) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>
      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :cedula, "Nº de Cédula", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :cedula, class: "form-control", :required => true %>
    </div>  
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :name, "Nombre", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control", :required => true %>
    </div>  
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :last_name, "Apellido", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :last_name, class: "form-control", :required => true %>
    </div>  
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :phone_number, "Nº de teléfono", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :phone_number, class: "form-control" %>
    </div>  
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :email, "E-mail", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control", :required => true %>
    </div>  
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :address, "Dirección", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :address, class: "form-control" %>
    </div>  
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :startdate, "Fecha de ingreso", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.date_field :startdate, :value => Date.today, class: "form-control" %>
    </div>  
  </div>
  <div class="form-group row">
    <div class="col-sm-2">
      <%= f.label :note, "Observaciones", class: "control-label" %><br>
    </div>
    <div class="col-sm-10">
      <%= f.text_area :note, class: "form-control" %>
    </div>  
  </div>
<% end %>

app/views/employees/destroy.js.erb
$('.delete_row').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>
<h1><%= Employee.new.table_name_to_show %></h1>
<p>
  <%= render 'layouts/modal_button', :btn_name => 'Nuevo Registro', :namespace_id => "new_employee" %>
  <%= render 'layouts/modal', :@employee => @new_employee, :modal_title => 'Nuevo Registro', :namespace_id => 'new_employee' %>
</p>
<div class="table-responsive">
  <table class="table table-sm table-hover table-striped table-bordered">
    <thead>
      <tr>
        <th>Nº de Cédula</th>
        <th>Nombre</th>
        <th>Apellido</th>
        <th>Número de teléfono</th>
        <th>E-mail</th>
        <th>Dirección</th>
        <th>Fecha de ingreso</th>
        <th>Balance de préstamo</th>
        <th>Observaciones</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @employees.reverse.each do |employee| %>
        <tr>
          <td><%= employee.cedula %></td>
          <td><%= employee.name %></td>
          <td><%= employee.last_name %></td>
          <td><%= employee.phone_number %></td>
          <td><%= employee.email %></td>
          <td><%= employee.address %></td>
          <td><%= employee.startdate %></td>
          <td><%= employee.get_loan_balance %></td>
          <td><%= employee.note %></td>
          <td>
            <%= render 'layouts/modal_button', :btn_name => 'Editar', :namespace_id => "edit_employee_#{employee.id}" %>
            <%= render 'layouts/modal', :@employee => employee, :modal_title => 'Editar', :namespace_id => "edit_employee_#{employee.id}" %>
          </td>
          <td><%= link_to '×', employee, method: :delete, data: { confirm: '¿Está seguro?' }, :remote => true, class: "close equis delete_row" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cedula:</strong>
  <%= @employee.cedula %>
</p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @employee.phone_number %>
</p>

<p>
  <strong>Email:</strong>
  <%= @employee.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Startdate:</strong>
  <%= @employee.startdate %>
</p>

<p>
  <strong>Note:</strong>
  <%= @employee.note %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>