config/routes.rb
Rails.application.routes.draw do

  concern :get_modal do
    get 'modal/:id/:button/:form', action: 'modal', as: 'modal', on: :collection
  end
  
  resources :payment_methods
  resources :accounts
  resources :cierres
  resources :auth_groups
  resources :employees, concerns: :get_modal
  resources :retenciones
  resources :inversions, concerns: :get_modal
  resources :ggs, concerns: :get_modal
  resources :deducciones_odts
  resources :comision_odts
  resources :odts, concerns: :get_modal
  resources :razon_socials, concerns: :get_modal
  resources :pools, concerns: :get_modal do
    get 'account/:id', action: 'account_index', as: 'account', on: :collection
    get 'account/:id/days/:days', action: 'days_index', as: 'days_account', on: :collection
  end
  root "pools#days_index", :id => 1, :days => 0

  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/approve/:token', to: 'permission_request#approve'
  get '/deny/:token', to: 'permission_request#deny'
  get '/ask', to: 'permission_request#ask', as: :ask_permission
  post '/set_permission', to: 'permission_request#set_permission'

end

app/models/auth_group.rb
class AuthGroup < ActiveRecord::Base
	has_and_belongs_to_many :users
	has_many :is_allowed_to, :dependent => :destroy
	has_many :action, through: :is_allowed_to

	def table_name_to_show
		'Grupo de Autorizacion'
	end
	def record_name_to_show
		return self.name
	end

	def can(action, *set_action)
		crud, model = action.split('_', 2) 	# crud = create, read, update or destroy
		model_permission= self.is_allowed_to.find_by( action_id: Action.where(name: model) )
		if model_permission.nil?
			unless set_action.empty?
				model_permission = self.is_allowed_to.create(action_id: Action.find_by(name: model).id )
				return model_permission.update "#{crud}?": set_action.first
			end
			return false
		end
		unless set_action.empty?
			return model_permission.update "#{crud}?": set_action.first
		end
		return model_permission["#{crud}?"]
	end
end

app/controllers/auth_groups_controller.rb
class AuthGroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_auth_group, only: [:show, :edit, :update, :destroy]

  # GET /auth_groups
  # GET /auth_groups.json
  def index
    @auth_groups = AuthGroup.all
  end

  # GET /auth_groups/1
  # GET /auth_groups/1.json
  def show
  end

  # GET /auth_groups/new
  def new
    @auth_group = AuthGroup.new
  end

  # GET /auth_groups/1/edit
  def edit
  end

  # POST /auth_groups
  # POST /auth_groups.json
  def create
    @auth_group = AuthGroup.new(auth_group_params)

    respond_to do |format|
      if @auth_group.save
        format.html { redirect_to @auth_group, success: AuthGroup.new.table_name_to_show.concat(' fue creada satisfactoriamente.') }
        format.json { render :show, status: :created, location: @auth_group }
      else
        format.html { render :new }
        format.json { render json: @auth_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /auth_groups/1
  # PATCH/PUT /auth_groups/1.json
  def update
    respond_to do |format|
      if @auth_group.update(auth_group_params)
        format.html { redirect_to @auth_group, success: AuthGroup.new.table_name_to_show.concat(' fue actualizado satisfactoriamente.') }
        format.json { render :show, status: :ok, location: @auth_group }
      else
        format.html { render :edit }
        format.json { render json: @auth_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auth_groups/1
  # DELETE /auth_groups/1.json
  def destroy
    @auth_group.destroy
    respond_to do |format|
      format.html { redirect_to auth_groups_url, success: AuthGroup.new.table_name_to_show.concat(' fue eliminado satisfactoriamente.') }
      format.json { head :no_content }
      format.js   { render 'layouts/destroy' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auth_group
      @auth_group = AuthGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auth_group_params
      params.require(:auth_group).permit(:name, :odt, :gg, :inversion, :employee, :retencione, :pool, :razon_social, :auth_group)
    end
end

app/helpers/auth_groups_helper.rb
module AuthGroupsHelper
end

app/views/auth_groups/_form.html.erb
<%= form_for(@auth_group, namespace: namespace_id, :html=> {:id => namespace_id}) do |f| %>
  <% if @auth_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auth_group.errors.count, "error") %> prohibited this auth_group from being saved:</h2>

      <ul>
      <% @auth_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :odt %><br>
    <%= f.check_box :odt %>
  </div>

  <div class="field">
    <%= f.label :gg %><br>
    <%= f.check_box :gg %>
  </div>

  <div class="field">
    <%= f.label :inversion %><br>
    <%= f.check_box :inversion %>
  </div>

  <div class="field">
    <%= f.label :employee %><br>
    <%= f.check_box :employee %>
  </div>

  <div class="field">
    <%= f.label :retencione %><br>
    <%= f.check_box :retencione %>
  </div>

  <div class="field">
    <%= f.label :pool %><br>
    <%= f.check_box :pool %>
  </div>

  <div class="field">
    <%= f.label :razon_social %><br>
    <%= f.check_box :razon_social %>
  </div>

  <div class="field">
    <%= f.label :auth_group %><br>
    <%= f.check_box :auth_group %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/auth_groups/destroy.js.erb
$('.delete_row').on('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/auth_groups/edit.html.erb
<h1>Editing Auth Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @auth_group %> |
<%= link_to 'Back', auth_groups_path %>

app/views/auth_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing <%= AuthGroup.new.table_name_to_show %></h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Acciones:</th>
      <th><%= link_to Odt.new.table_name_to_show, odts_path %></th>
      <th><%= link_to Gg.new.table_name_to_show, ggs_path %></th>
      <th><%= link_to Inversion.new.table_name_to_show, inversions_path %></th>
      <th><%= link_to Employee.new.table_name_to_show, employees_path %></th>
      <th><%= link_to Retencione.new.table_name_to_show, retenciones_path %></th>
      <th><%= link_to Pool.new.table_name_to_show, pools_path %></th>
      <th><%= link_to RazonSocial.new.table_name_to_show, razon_socials_path %></th>
      <th><%= link_to AuthGroup.new.table_name_to_show, auth_groups_path %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @auth_groups.each do |auth_group| %>
      <tr>
        <td><%= auth_group.name %>:</td>
        <td><%= auth_group.odt %></td>
        <td><%= auth_group.gg %></td>
        <td><%= auth_group.inversion %></td>
        <td><%= auth_group.employee %></td>
        <td><%= auth_group.retencione %></td>
        <td><%= auth_group.pool %></td>
        <td><%= auth_group.razon_social %></td>
        <td><%= auth_group.auth_group %></td>
        <td><%= link_to 'Show', auth_group %></td>
        <td><%= link_to 'Edit', edit_auth_group_path(auth_group) %></td>
        <td><%= link_to '×', auth_group, method: :delete, data: { confirm: '¿Está seguro?' }, :remote => true, class: "close equis delete_row" %></td>
        </tr>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New '+ AuthGroup.new.table_name_to_show, new_auth_group_path %>

app/views/auth_groups/new.html.erb
<h1>New Auth Group</h1>

<%= render 'form' %>

<%= link_to 'Back', auth_groups_path %>

app/views/auth_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @auth_group.name %>
</p>
<p>
  <strong><%= link_to Odt.new.table_name_to_show, odts_path %>:</strong>
  <%= @auth_group.odt %>
</p>
<p>
  <strong><%= link_to Gg.new.table_name_to_show, ggs_path %>:</strong>
  <%= @auth_group.gg %>
</p>
<p>
  <strong><%= link_to Inversion.new.table_name_to_show, inversions_path %>:</strong>
  <%= @auth_group.inversion %>
</p>
<p>
  <strong><%= link_to Employee.new.table_name_to_show, employees_path %>:</strong>
  <%= @auth_group.employee %>
</p>
<p>
  <strong><%= link_to Retencione.new.table_name_to_show, retenciones_path %>:</strong>
  <%= @auth_group.retencione %>
</p>
<p>
  <strong><%= link_to Pool.new.table_name_to_show, pools_path %>:</strong>
  <%= @auth_group.pool %>
</p>
<p>
  <strong><%= link_to RazonSocial.new.table_name_to_show, razon_socials_path %>:</strong>
  <%= @auth_group.razon_social %>
</p>
<p>
  <strong><%= link_to AuthGroup.new.table_name_to_show, auth_groups_path %>:</strong>
  <%= @auth_group.auth_group %>
</p>

<%= link_to 'Edit', edit_auth_group_path(@auth_group) %>
<%= link_to 'Back', auth_groups_path %>