config/routes.rb
Rails.application.routes.draw do

  concern :get_modal do
    get 'modal/:id/:button/:form', action: 'modal', as: 'modal', on: :collection
  end
  
  resources :payment_methods
  resources :accounts
  resources :cierres
  resources :auth_groups
  resources :employees, concerns: :get_modal
  resources :retenciones
  resources :inversions, concerns: :get_modal
  resources :ggs, concerns: :get_modal
  resources :deducciones_odts
  resources :comision_odts
  resources :odts, concerns: :get_modal
  resources :razon_socials, concerns: :get_modal
  resources :pools, concerns: :get_modal do
    get 'account/:id', action: 'account_index', as: 'account', on: :collection
    get 'account/:id/days/:days', action: 'days_index', as: 'days_account', on: :collection
  end
  root "pools#days_index", :id => 1, :days => 0

  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/approve/:token', to: 'permission_request#approve'
  get '/deny/:token', to: 'permission_request#deny'
  get '/ask', to: 'permission_request#ask', as: :ask_permission
  post '/set_permission', to: 'permission_request#set_permission'

end

app/models/comision_odt.rb
class ComisionOdt < ActiveRecord::Base
	belongs_to :odt
	belongs_to :employee
	def table_name_to_show
		'Porcentaje de Comision'
	end
	def record_name_to_show
		return self.p_comision
	end
end

app/controllers/comision_odts_controller.rb
class ComisionOdtsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comision_odt, only: [:show, :edit, :update, :destroy]

  # GET /comision_odts
  # GET /comision_odts.json
  def index
    permission_denied and return  if current_user.cannot 'read_comision_odt'
    @comision_odts = ComisionOdt.all    
    @new_comision_odt = ComisionOdt.new
  end

  # GET /comision_odts/1
  # GET /comision_odts/1.json
  def show
  end

  # GET /comision_odts/new
  def new
    @comision_odt = ComisionOdt.new
  end

  # GET /comision_odts/1/edit
  def edit
  end

  # POST /comision_odts
  # POST /comision_odts.json
  def create
    permission_denied and return  if current_user.cannot 'create_comision_odt'
    @comision_odt = ComisionOdt.new(comision_odt_params)

    respond_to do |format|
      if @comision_odt.save
        format.html { redirect_to comision_odts_url, success: @comision_odt.table_name_to_show.concat(' fue creada satisfactoriamente.') }
        format.json { render :show, status: :created, location: @comision_odt }
      else
        format.html { render :new }
        format.json { render json: @comision_odt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comision_odts/1
  # PATCH/PUT /comision_odts/1.json
  def update
    permission_denied and return  if current_user.cannot 'update_comision_odt'
    respond_to do |format|
      if @comision_odt.update(comision_odt_params)
        format.html { redirect_to comision_odts_url, success: @comision_odt.table_name_to_show.concat(' fue actualizado satisfactoriamente.') }
        format.json { render :show, status: :ok, location: @comision_odt }
      else
        format.html { render :edit }
        format.json { render json: @comision_odt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comision_odts/1
  # DELETE /comision_odts/1.json
  def destroy
    @comision_odt.destroy
    respond_to do |format|
      format.html { redirect_to comision_odts_url, success: 'Comision odt fue eliminado satisfactoriamente.' }
      format.json { head :no_content }
      format.js   { render 'layouts/destroy' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comision_odt
      @comision_odt = ComisionOdt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comision_odt_params
      params.require(:comision_odt).permit(:odt_id, :employee_id, :p_comision)
    end
end

app/helpers/comision_odts_helper.rb
module ComisionOdtsHelper
end

app/views/comision_odts/_form.html.erb
<%= form_for(@comision_odt, namespace: namespace_id) do |f| %>
  <% if @comision_odt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comision_odt.errors.count, "error") %> prohibited this comision_odt from being saved:</h2>
      <ul>
      <% @comision_odt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= label_tag( 'comision_odt_odt_id', Odt.new.table_name_to_show ) %><br>
    <%= f.select( :odt_id, options_for_select( Odt.all.collect{ |e| [e.record_name_to_show, e.id ] }, @comision_odt.odt_id ), :prompt => '--Seleccionar--' ) %>
  </div>
  <div class="field">
    <%= label_tag( 'comision_odt_employee_id', Employee.new.table_name_to_show ) %><br>
    <%= f.select( :employee_id, options_for_select( Employee.all.collect{ |e| [e.record_name_to_show, e.id ] }, @comision_odt.employee_id ), :prompt => '--Seleccionar--' ) %>
  </div>
  <div class="field">
    <%= f.label :p_comision %><br>
    <%= f.text_field :p_comision %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

   

app/views/comision_odts/destroy.js.erb
$('.delete_row').bind('ajax:success', function() {
   $(this).closest('tr').fadeOut();
});

app/views/comision_odts/edit.html.erb
<h1>Editing <%= ComisionOdt.new.table_name_to_show %></h1>

<%= render 'form' %>

<%= link_to 'Show', @comision_odt %> |
<%= link_to 'Back', comision_odts_path %>

app/views/comision_odts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Listing <%= ComisionOdt.new.table_name_to_show %></h1>
<p>
  <%= render 'layouts/modal_button', :btn_name => 'Nuevo Registro', :namespace_id => "new_comision_odt" %>
  <%= render 'layouts/modal', :@comision_odt => @new_comision_odt, :modal_title => 'Añadir Comision', :namespace_id => 'new_comision_odt' %>
</p>
<div class="table-responsive">
  <table  class="table table-sm table-hover table-striped table-bordered">
    <thead>
      <tr>
        <th><%= link_to Odt.new.table_name_to_show, odts_path %></th>
        <th><%= link_to Employee.new.table_name_to_show, employees_path %></th>
        <th><%= link_to ComisionOdt.new.table_name_to_show, comision_odts_path %></th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @comision_odts.each do |comision_odt| %>
        <tr>
          <td><%= link_to comision_odt.odt.record_name_to_show, comision_odt.odt %></td>
          <td><%= link_to comision_odt.employee.record_name_to_show, comision_odt.employee %></td>
          <td><%= comision_odt.p_comision %></td>
          <td>
            <%= render 'layouts/modal_button', :btn_name => 'Editar', :namespace_id => "edit_comision_odt_#{comision_odt.id}" %>
            <%= render 'layouts/modal', :@comision_odt => comision_odt, :modal_title => 'Editar', :namespace_id => "edit_comision_odt_#{comision_odt.id}" %>
          </td>
          <td><%= link_to '×', comision_odt, method: :delete, data: { confirm: '¿Está seguro?' }, :remote => true, class: "close equis delete_row" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/comision_odts/new.html.erb
<h1>New Comision Odt</h1>

<%= render 'form' %>

<%= link_to 'Back', comision_odts_path %>

app/views/comision_odts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= Odt.new.table_name_to_show %>:</strong>
  <%= ( link_to @comision_odt.odt.record_name_to_show, @comision_odt.odt ) if @comision_odt.odt %>
</p>

<p>
  <strong><%= Employee.new.table_name_to_show %>:</strong>
  <%= ( link_to @comision_odt.employee.record_name_to_show, @comision_odt.employee ) if @comision_odt.employee %>
</p>

<p>
  <strong><%= ComisionOdt.new.table_name_to_show %>:</strong>
  <%= @comision_odt.p_comision %>
</p>

<%= link_to 'Edit', edit_comision_odt_path(@comision_odt) %> |
<%= link_to 'Back', comision_odts_path %>